version: '3.7'

services:
  django:
    container_name: flowchart_web
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE
      - PYTHONUNBUFFERED=0
    command: python manage.py runserver 0.0.0.0:8005
    volumes:
      - .:/opt/services/app/src:Z
    expose:
      - 8005
    ports:
      - "8005:8005"
    env_file:
      - .env
    networks:
      - flowchart_network
    links:
      - database
    depends_on:
      - database

  database:
    image: postgres:12
    container_name: flowchart_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - flowchart_network

networks:
  flowchart_network:
    driver: bridge

volumes:
  db:
