# Generated by Django 4.1.7 on 2023-03-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commonuser",
            name="user_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Employee"),
                    (2, "Supervisor"),
                    (3, "Business analyst"),
                    (4, "Super admin"),
                    (5, "Director"),
                ],
                default=1,
                verbose_name="User type",
            ),
        ),
    ]
