# Generated by Django 4.1.7 on 2023-03-28 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common_users", "0002_alter_commonuser_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="commonuser",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Parent",
            ),
        ),
    ]
