# Generated by Django 4.1.7 on 2023-03-26 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessProcess",
            fields=[
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Active"),
                            (2, "Approved"),
                            (3, "Canceled"),
                        ],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Data"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_processes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business process",
                "verbose_name_plural": "Business processes",
                "db_table": "business_process",
            },
        ),
    ]
