# Generated by Django 4.1.7 on 2023-03-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_processes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprocess",
            name="title",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="businessprocess",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Draft"),
                    (2, "Active"),
                    (3, "Approved"),
                    (4, "Canceled"),
                ],
                default=1,
                verbose_name="Status",
            ),
        ),
    ]
