# Generated by Django 4.1.7 on 2023-03-27 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "business_processes",
            "0002_businessprocess_title_alter_businessprocess_status",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="businessprocess",
            table="business_processes",
        ),
        migrations.CreateModel(
            name="BusinessProcessToBe",
            fields=[
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Data"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_process_to_be",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "business_process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_process_as_is",
                        to="business_processes.businessprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business process",
                "verbose_name_plural": "Business processes",
                "db_table": "to_be_business_processes",
            },
        ),
    ]
