# Generated by Django 4.1.7 on 2023-03-27 20:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "business_processes",
            "0003_alter_businessprocess_table_businessprocesstobe",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BusinessProcess",
            new_name="BusinessProcessAsIs",
        ),
        migrations.AlterModelTable(
            name="businessprocessasis",
            table="as_is_business_processes",
        ),
    ]
