# Generated by Django 4.1.7 on 2023-03-27 21:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "business_processes",
            "0004_rename_businessprocess_businessprocessasis_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="businessprocesstobe",
            old_name="business_process",
            new_name="business_process_as_is",
        ),
    ]
